#include "a18_optimizer.h"
#include <iostream>
using namespace a18;
size_t passed=0;
void check(bool b,const std::string&n){if(!b)throw std::runtime_error("TEST_FAILED:"+n);++passed;std::cout<<"PASS "<<n<<'\n';}
void decision(const I&p,const I&d,const std::string&s,const std::string&n){check(choose(p,d).status==s,n);}
void thrown(const std::function<void()>&fn,const std::string&s,const std::string&n){try{fn();}catch(const std::exception&e){check(exceptionStatus(e)==s,n);return;}check(false,n);}
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("OUTPUT required");std::string out=argv[1];fs::create_directory(out);
 decision(1,1,"ACCEPT","positive");decision(1,-1,"REJECT","negative D");decision(1,0,"REJECT","zero D");decision(0,1,"REJECT","zero P");decision(-1,1,"REJECT","negative P");decision(1,I(M(-1e-20),M(1e-20)),"NUMERIC_REDUCTION_UNRESOLVED","uncertain sign");decision(1,I(M(1),M(1.01)),"NUMERIC_REDUCTION_UNRESOLVED","width");decision(1,.0001,"REJECT","low fidelity");decision(1,.001,"REJECT","equal fidelity");decision(1,.002,"ACCEPT","high fidelity");decision(1,I(M(std::nextafter(.001,0)),M(std::nextafter(.001,1))),"NUMERIC_REDUCTION_UNRESOLVED","fidelity straddle");decision(1,I(M(.001),M(std::nextafter(.001,1))),"NUMERIC_REDUCTION_UNRESOLVED","conversion cannot cross threshold");
 I narrow(M(op(M(.001),M(1e-40),DOWN,mpfr_add)),M(op(M(.001),M(2e-40),UP,mpfr_add)));check(choose(1,narrow).status=="NUMERIC_REDUCTION_UNRESOLVED"&&choose(1,narrow).reason=="FIDELITY_CONVERSION","true ratio above threshold but RNDD double at threshold fails");
 I bad(1);mpfr_set_d(&bad.lo.x,std::numeric_limits<double>::infinity(),NEAR);decision(bad,1,"NUMERIC_REFERENCE_NONFINITE","nonfinite bound");thrown([]{I x(std::numeric_limits<double>::quiet_NaN());},"NUMERIC_REFERENCE_NONFINITE","nonfinite input");
 I cancel=paired(Vec{I(1e16)},Vec{I(std::nextafter(1e16,0))});check(M(0)<cancel.lo,"large cancellation");I falseD=paired(Vec{I(1e16)},Vec{I(std::nextafter(1e16,INFINITY))});decision(1,falseD,"REJECT","false native decrease cannot override certificate");check(norm(Vec{I(0),I(0),I(0)}).lo.d()==0,"zero norm hull");thrown([]{less(I(M(-1),M(1)),I(0));},"NUMERIC_REFERENCE_UNSUPPORTED","uncertain branch");thrown([]{fun(I(2),"acos");},"NUMERIC_REFERENCE_UNSUPPORTED","acos domain");thrown([]{fun(I(2),"tan");},"NUMERIC_REFERENCE_UNSUPPORTED","tan domain");
 Raw raw;raw[{"CONST",0,"log_near_pi_threshold"}]={{.001}};Evaluator ev(raw);thrown([&]{ev.log(Mat{{1,0,0},{0,-1,0},{0,0,-1}},"BASE",0,"imu_log");},"NUMERIC_REFERENCE_UNSUPPORTED","near pi");thrown([&]{ev.residual(a18::Factor{0,"UNKNOWN",{},1},"BASE");},"NUMERIC_REFERENCE_UNSUPPORTED","unknown factor");
 auto q=choose(I(3),I(1));check(q.status=="ACCEPT"&&M(q.fidelity)<=q.ratio.lo&&q.ratio.lo<=op(M(1),M(3),UP,mpfr_div),"conservative division conversion");
 NonlinearFactorGraph graph;Values initial;initial.insert(Symbol('v',0),Vector3(1,0,0));graph.add(PriorFactor<Vector3>(Symbol('v',0),Vector3::Zero(),noiseModel::Unit::Create(3)));LevenbergMarquardtParams p;p.relativeErrorTol=0;p.setLinearSolverType("SEQUENTIAL_CHOLESKY");
 for(const auto&kind:std::vector<std::string>{"NUMERIC_REFERENCE_NONFINITE","NUMERIC_REDUCTION_UNRESOLVED","NUMERIC_REFERENCE_UNSUPPORTED"}){std::string dir=out+"/"+kind;fs::create_directory(dir);CertifiedLm lm(graph,initial,p,{},dir,[kind]{throw std::runtime_error(kind+":INJECTED_CPP_TRIAL_EXCEPTION");});lm.iterate();check(lm.failure.find(kind)==0&&lm.calls==1&&lm.solves==1&&lm.trials==1&&lm.unresolved==1&&lm.accepted==0&&lm.rejected==0&&lm.iterations()==0&&lm.getInnerIterations()==0,"actual C++ exception counters "+kind);std::ifstream f(dir+"/trials.csv");std::string content((std::istreambuf_iterator<char>(f)),{});check(content.find(","+kind+",")!=std::string::npos,"actual C++ trial status "+kind);}
 uifgo::CheckedLmOptions o;o.max_iterations=50;o.policy=uifgo::ConditionalLmPolicy::GTSAM_CHECK_AND_NAVIGATION_STATIONARITY_CONTINUE_LAMBDA_SEARCH_V2;auto r=runCertified(1,graph,initial,o,{},out+"/vector_fixture");check(r.converged&&r.convergence.iterate_call_count==2&&r.convergence.accepted_update_count==2&&r.convergence.lambda_trial_count==2&&r.iterations==2&&r.inner_iterations==2,"native counters original generic AND stationarity");
 // A real provider chain update must supply its current nonzero constant to the callback.
 using namespace uifgo;Config cfg;cfg.fixed_beta_by_link["0:1"]=.03;AnchorConfig anchor;anchor.id=1;anchor.pos=Point3(0,0,0);cfg.anchors.push_back(anchor);cfg.lever_arm_init=Point3(0,0,0);cfg.calib_lever=cfg.calib_anchor=cfg.calib_range_bias=cfg.calib_td=false;
 PaperInputPlan plan;plan.keyframes.resize(1);ObservationRecord obs;obs.obs_id=1;obs.tag_id=0;obs.anchor_id=1;obs.sensor_time=0;obs.keyframe_id=0;obs.raw_range=2.03;obs.nominal_sigma=.05;obs.valid=obs.planned=true;plan.observations.push_back(obs);
 Values v;v.insert(Symbol('x',0),Pose3(Rot3(),Point3(1,0,0)));v.insert(Symbol('v',0),Vector3(0,0,0));v.insert(Symbol('b',0),imuBias::ConstantBias());NonlinearFactorGraph g;g.add(boost::make_shared<PaperPosePriorFactor>(Symbol('x',0),v.at<Pose3>(Symbol('x',0)),noiseModel::Isotropic::Sigma(6,.01)));g.add(PriorFactor<Vector3>(Symbol('v',0),Vector3::Zero(),noiseModel::Unit::Create(3)));g.add(PriorFactor<imuBias::ConstantBias>(Symbol('b',0),imuBias::ConstantBias(),noiseModel::Unit::Create(6)));g.add(MakeUwbFactor(Symbol('x',0),0,0,0,anchor.pos,cfg.lever_arm_init,obs.raw_range,obs.nominal_sigma,false,false,false,.03));FactorMeta meta;meta.factor_index=3;meta.factor_type="uwb_range";meta.obs_id=1;
 DiscoveryOptions opts;opts.max_outer_iterations=3;opts.conditional_lm=o;opts.fused_lasso.lambda_l1=4;opts.fused_lasso.lambda_tv=20;opts.fused_lasso.max_iterations=10000;DiscoveryContext ctx;ctx.solver_config_hash="a18-policy-sha256:engineering-fixture";DevelopmentStage1Request req;req.policy="PAPER_CERTIFIED_PAIR_REDUCTION_V1";req.role="development";req.implementation_identity=ctx.solver_config_hash;bool saw=false;
 req.conditional_navigation=[&](size_t outer,const NonlinearFactorGraph&cg,const Values&base,const CheckedLmOptions&co,const std::vector<DevelopmentRangeConstant>&rs){if(outer==1)return runCertified(outer,cg,base,co,rs,out+"/provider_first");check(rs.size()==1&&rs[0].conditional_beta>.03,"actual chain nonzero dynamic bias");saw=true;LiveGraph live(cg,rs);auto lin=cg.linearize(base);auto dir=out+"/nonzero_native";fs::create_directory(dir);CertifiedLm lm(cg,base,p,rs,dir);auto de=lm.fixedDirection(*lin);LevenbergMarquardtOptimizer native(cg,base,p);auto nativeDelta=native.solve(native.buildDampedSystem(*lin,VectorValues()),p);for(auto&kv:de)check((kv.second-nativeDelta.at(kv.first)).norm()==0,"nonzero native direction "+DefaultKeyFormatter(kv.first));auto trial=base.retract(de);auto data=live.pair(base,trial,de,*lin);auto c=certify(data);dump(dir,data);writeLinear(dir,*lin,de);write(dir+"/certificate.json",c);Evaluator e(data.raw);for(auto&f:data.factors)for(auto phase:{"BASE","TRIAL"}){auto ref=e.residual(f,phase);const Values&state=std::string(phase)=="BASE"?base:trial;auto nf=boost::dynamic_pointer_cast<NoiseModelFactor>(cg[f.index]);Vector un=nf->unwhitenedError(state);for(size_t i=0;i<ref.size();++i)check(std::abs(ref[i].lo.d()-un[i])<=1e-8,"nonzero formula");auto white=mv(e.mat("CONST",f.index,"whitening_R"),ref);Vector wn=nf->whitenedError(state);for(size_t i=0;i<white.size();++i)check(std::max(std::abs(white[i].lo.d()-wn[i]),std::abs(white[i].hi.d()-wn[i]))<=1e-6,"nonzero full whitening formula");}check(c.decision.status=="ACCEPT","nonzero certificate");CheckedLmResult result;result.values=base;result.reason="ENGINEERING_CAPTURE_STOP";return result;};
 auto dr=AutomaticSupportProvider(opts).RunDevelopmentStage1(g,v,{meta},plan,cfg,ctx,nullptr,&req);std::cout<<"PROVIDER_FIXTURE "<<DiscoveryStatusName(dr.status)<<":"<<dr.reason<<"\n";check(saw&&dr.status==DiscoveryStatus::CONDITIONAL_LM_FAILED&&dr.reason=="ENGINEERING_CAPTURE_STOP","provider real chain and bounded capture");check(dr.partition.schema=="A18_STAGE1_DIAGNOSTIC_ONLY","nonconsumable schema");req.role="validation";auto denied=AutomaticSupportProvider(opts).RunDevelopmentStage1(g,v,{meta},plan,cfg,ctx,nullptr,&req);check(denied.status==DiscoveryStatus::INVALID_INPUT,"nondevelopment rejected");req.role="development";ctx.solver_config_hash="old";denied=AutomaticSupportProvider(opts).RunDevelopmentStage1(g,v,{meta},plan,cfg,ctx,nullptr,&req);check(denied.status==DiscoveryStatus::INVALID_INPUT,"identity mismatch rejected");
 std::cout<<"ALL_PASS checks="<<passed<<'\n';return 0;
 }catch(const std::exception&e){std::cerr<<exceptionStatus(e)<<":"<<e.what()<<'\n';return 1;}}
