#!/usr/bin/env python3
"""Generate the five complete v6 runtime configs from the reviewed v5 base."""

from pathlib import Path
import yaml


ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "config" / "realtime_uwb_imu_pl_research.yaml"
PROFILES = (
    "off",
    "uwb_order1",
    "imu_order1",
    "joint_order1",
    "joint_order2",
)


def generate() -> None:
    source = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    for profile in PROFILES:
        cfg = yaml.safe_load(yaml.safe_dump(source, sort_keys=False))
        cfg["schema_version"] = "uwb-imu-pl/v6"
        cfg["output"]["schema_version"] = "uwb-imu-pl/v6"
        cfg["output"]["root"] = f"results/fde_profiles/{profile}"
        # Compact-by-default evidence; timing remains enabled.
        cfg["output"]["write_residuals"] = False
        cfg["output"]["write_hypothesis_evidence"] = False
        cfg["output"]["write_candidates"] = False
        cfg["incremental"]["relinearize_skip"] = 1
        # The target window is 10 epochs plus a 10-epoch recovery margin.  A
        # 30-epoch lag keeps that full contract while reaching real
        # marginalization early enough for bounded pilot/full campaigns.
        cfg["incremental"]["fixed_lag_epochs"] = 30
        # Preserve the historical synthetic campaign numbers exactly.  P0-07
        # deliberately does not treat this conversion comment as calibration:
        # the emitted model remains UNQUALIFIED until external evidence binds
        # effective-interval sigma semantics and the shared-sample trapezoid
        # correlation overbound.
        cfg["imu"]["accelerometer_sigma"] = 0.01 / (200.0 ** 0.5)
        cfg["imu"]["gyroscope_sigma"] = 0.001 / (200.0 ** 0.5)
        for key in (
            "single_faults_enabled",
            "double_faults_enabled",
            "max_fault_order",
        ):
            cfg["fault_models"].pop(key, None)
        cfg["fde"]["profile"] = profile
        cfg["fde"]["on_no_valid_action"] = "discard"
        cfg["fde"]["on_integrity_model_invalid"] = "discard"
        cfg["publication"] = {
            "allow_unprotected_output": True,
            "protected_output_enabled": False,
            "deadline_ms": 40.0,
        }
        cfg["realtime"].update(
            {
                # Exercise the actual body-to-tag measurement model in every
                # profile rather than silently validating a co-located tag.
                "lever_arm_body_m": [0.25, -0.10, 0.08],
                "max_queued_events": 8192,
                "imu_overflow_policy": "invalidate_and_reinitialize",
                "uwb_overflow_policy": "drop_oldest_unprocessed_uwb",
            }
        )
        target = ROOT / "config" / f"fde_{profile}.yaml"
        header = (
            "# GENERATED by tools/generate_fde_profile_configs.py; edit the "
            "reviewed base/generator.\n"
            "# Research-only configuration; formal_eligible remains false "
            "without calibration/review.\n"
        )
        target.write_text(
            header + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8"
        )


if __name__ == "__main__":
    generate()
